name = "Sugar"
author = "Harvel"
version = "3.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d7b04921b301e074b2f3da208338e00a5ad936f696c015f133fa9588ac47025"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[export]
[export.curseforge]
project-id = 560248

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
