name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87f35fc07f9f46612d17ced37cd3ef10364be42f9154fc3f376e973ab6f31326"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"

[export]
[export.curseforge]
project-id = 560248

[options]
