name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4413a1354b5a76bad6a4db74eaf6054b748acbb4f00dce7f69af66cf593b446"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"

[export]
[export.curseforge]
project-id = 560248

[options]
