name = "Sugar"
author = "Harvel"
version = "2.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d19b70b9b66df79859e82b7a2c05f7b67e186928cb4e50319a59b6cf0e249fe"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[export]
[export.curseforge]
project-id = 560248
