name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f14236afa3b245e3d49a5dbc11836f056b0f91c518d7713282317caa4410349e"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"

[export]
[export.curseforge]
project-id = 560248

[options]
