name = "Sugar"
author = "Harvel"
version = "3.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb62e9c0c2c9544368da911f4fd152a41eb7c07da21840344f8e5f98d1820d21"

[versions]
minecraft = "1.19.4"
quilt = "0.18.6"

[export]
[export.curseforge]
project-id = 560248

[options]
