name = "Sugar"
author = "Harvel"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b0b35a5510465316185c15c8379e7cf2c242eea5965ecfc0e08072f3bd64123"

[versions]
fabric = "0.14.6"
minecraft = "1.19"

[export]
[export.curseforge]
project-id = 560248
