name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3373e001fd74fc6e7ffc7af4f3b1c0638815bef8e9d22b0167386d01bd5d31a0"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"

[export]
[export.curseforge]
project-id = 560248
