name = "Sugar"
author = "Harvel"
version = "2.2.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be5a85b9fa9d2d1b1ab0a074ca471120979dcd3cb6170807bb3e73f064b25121"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[export]
[export.curseforge]
project-id = 560248
