name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aee57462419d2552caac772dc8d9fec5eda8e46f1397adf2adc4330c61ae0f4"

[versions]
minecraft = "1.19.3"
quilt = "0.17.7"

[export]
[export.curseforge]
project-id = 560248
