name = "Sugar"
author = "Harvel"
version = "4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dd06486dee0f3321d4bb58556d82209278f154732a0111a2b31283401bc29d9"

[versions]
minecraft = "1.20.1"
quilt = "0.19.0"

[export]
[export.curseforge]
project-id = 560248

[options]
acceptable-game-versions = ["1.20"]
