name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fef40986132595bddbe70b5ca718987d62cb366d1c04fa186cb8b64f4c02cbe8"

[versions]
minecraft = "1.19.3"
quilt = "0.17.7"

[export]
[export.curseforge]
project-id = 560248
