name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cdd537b7ab3d4c8639b9c2358ec58f871fb09ce04a0cc5d2298a33f1b7e8730"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"

[export]
[export.curseforge]
project-id = 560248
