name = "Sugar"
author = "Harvel"
version = "2.2.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1019e9c266a16041d8897151b02cd8d91f9df4976add8db70b38c60fe7c6770d"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[export]
[export.curseforge]
project-id = 560248
