name = "Sugar"
author = "Harvel"
version = "2.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb7e8bcadb971f1274d94126619241e60e7b7a5c135093df18f66567d722085e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[export]
[export.curseforge]
project-id = 560248
