name = "Sugar"
author = "Harvel"
version = "3.1.0-pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bfcfb9c826e66b44a0f8b29712447a78a5232ddf1cc5a46ba67deebccc8c31d"

[versions]
minecraft = "1.19.1"
quilt = "0.17.1"

[export]
[export.curseforge]
project-id = 560248
