name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8de3e033d6553523657e63b665688665860f5d2e9376487b25e3a31b1760cba1"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"

[export]
[export.curseforge]
project-id = 560248

[options]
