name = "Sugar"
author = "Harvel"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a970621fea9818cceb6cf13d2cf48398d28c144ff3b67cb68057f97636955fd"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"

[export]
[export.curseforge]
project-id = 560248

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
