name = "Sugar"
author = "Harvel"
version = "2.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5b9f878a512c42694a424a727d0dd2a3188c529cc923b6740bdc0bb74d30058"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[export]
[export.curseforge]
project-id = 560248
