name = "Sugar"
author = "Harvel"
version = "3.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a9243d5232725d6b7fa1be107111e185d1bab7fb3aa3f78024be714f5f9fe4"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0"

[export]
[export.curseforge]
project-id = 560248
