name = "Sugar"
author = "Harvel"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59b3340fc7c83b8fa2949e149824ff79645b42b801f9e4dbddb48ddf94777967"

[versions]
fabric = "0.14.8"
minecraft = "1.19"

[export]
[export.curseforge]
project-id = 560248
