name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4654d97be2dea27b10622bb1f887ff7af32cb43bb6745374e5d1ad5cb03b5daf"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"

[export]
[export.curseforge]
project-id = 560248
