name = "Sugar"
author = "Harvel"
version = "2.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c0999685724e19f70cdb6ebef5ce1f213de9adde0dc8cbd7fa51e8f366d284"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[export]
[export.curseforge]
project-id = 560248
