name = "Sugar"
author = "Harvel"
version = "3.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89729ae1fd5f36f5a77167bc51518ccc3ac752625fd894e74728aa85b52419c7"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"

[export]
[export.curseforge]
project-id = 560248

[options]
