name = "Sugar"
author = "Harvel"
version = "2.2.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b18c3711d03c4395c65e42c1097ab72a5f03c6a7f57ed5db00a9f8abebc565c5"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[export]
[export.curseforge]
project-id = 560248
