name = "Sugar"
author = "Harvel"
version = "4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a46387656ea68858e5175755f504572132c84010cc29213027c00ccb3713c86"

[versions]
minecraft = "1.20.1"
quilt = "0.19.0"

[export]
[export.curseforge]
project-id = 560248

[options]
acceptable-game-versions = ["1.20"]
