enableSodiumMenu = false
useBlockStateCulling = true
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingDepth = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
minecraft = true
