name = "Animatica"
filename = "animatica-0.5+1.18.2.jar"
side = "client"

[download]
url = "https://raw.githubusercontent.com/HarvelsX/Sugar/packwiz/1.19.x/mods/animatica-0.5+1.18.2.jar"
hash-format = "sha1"
hash = "558e099696c1c7a7b9bc7d804a9cd85a0c6a4eac"

[update]
[update.modrinth]
mod-id = "PRN43VSY"
version = "uoIGWJxI"
[update.curseforge]
file-id = 3664303
project-id = 533006
