name = "AntiGhost"
filename = "antighost-1.18.2-fabric0.47.10-1.1.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Jw3Wx1KR/versions/1.18.2-fabric0.47.10-1.1.4/antighost-1.18.2-fabric0.47.10-1.1.4.jar"
hash-format = "sha1"
hash = "b9a690827fdaa60388bc297d6bf339c7ffd68261"

[update]
[update.modrinth]
mod-id = "Jw3Wx1KR"
version = "JX1vBTrB"
[update.curseforge]
file-id = 3687749
project-id = 273279
