name = "Capes"
filename = "Capes-1.3.1+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/89Wsn8GD/versions/1.3.1+1.18.2/Capes-1.3.1%2B1.18.2.jar"
hash-format = "sha1"
hash = "407dc8d3a02785775deab32033d227a690481083"

[update]
[update.modrinth]
mod-id = "89Wsn8GD"
version = "IiXFyaYT"
[update.curseforge]
file-id = 3780643
project-id = 408481
