name = "CIT Resewn"
filename = "CITResewn-1.0.1+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/otVJckYQ/versions/1.0.1+1.18.2/CITResewn-1.0.1%2B1.18.2.jar"
hash-format = "sha1"
hash = "cf16285fe5c6c8e03beff83b4b4b8ee054a381d0"

[update]
[update.modrinth]
mod-id = "otVJckYQ"
version = "UpVioyBK"
[update.curseforge]
file-id = 3697502
project-id = 521427