name = "CustomHud"
filename = "custom_hud-2.0.0+1.19.jar"
side = "client"

[download]
url = "https://raw.githubusercontent.com/HarvelsX/Sugar/packwiz/1.19.x/mods/custom_hud-2.0.0%2B1.19.jar"
hash-format = "sha1"
hash = "ec3ff298be6be2046e440342d3a28388e0155d6f"

[update]
[update.modrinth]
mod-id = "6jis0UTI"
version = "kbUNur6K"
[update.curseforge]
file-id = 3721716
project-id = 406984
