name = "CustomHud"
filename = "custom_hud-2.0.0-beta.2+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/6jis0UTI/versions/v2.0.0-beta.2+1.18/custom_hud-2.0.0-beta.2%2B1.18.2.jar"
hash-format = "sha1"
hash = "491bb0feff7fc2d07af7c9d943d8ba603c5eb535"

[update]
[update.modrinth]
mod-id = "6jis0UTI"
version = "kbUNur6K"
[update.curseforge]
file-id = 3721716
project-id = 406984
