name = "Enhanced Block Entities"
filename = "enhancedblockentities-0.6+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/OVuFYfre/versions/0.6+1.18.2/enhancedblockentities-0.6%2B1.18.2.jar"
hash-format = "sha1"
hash = "d4a4ce2f0249cd636eb3f820225082645885bd74"

[update]
[update.modrinth]
mod-id = "OVuFYfre"
version = "VOB3iJkd"
[update.curseforge]
file-id = 3717795
project-id = 452046
