name = "Krypton"
filename = "krypton-0.2.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/fQEb0iXm/versions/0.2.0/krypton-0.2.0.jar"
hash-format = "sha1"
hash = "4ef667c6e053dd22e3e8cfa6299a75069af858ad"

[update]
[update.curseforge]
file-id = 3821821
project-id = 428912
[update.modrinth]
mod-id = "fQEb0iXm"
version = "UJ6FlFnK"
