name = "Plumbum"
filename = "plumbum-0.1.0-dev.dd17cd2+mc1.19.jar"
side = "client"

[download]
url = "https://raw.githubusercontent.com/HarvelsX/Sugar/packwiz/1.19.x/mods/plumbum-0.1.0-dev.dd17cd2%2Bmc1.19.jar"
hash-format = "sha1"
hash = "f5caf5d12d4bf63eab9345d4516cb8e87c501956"

# [update]
# [update.curseforge]
# file-id = 3840292
# project-id = 459496
# [update.modrinth]
# mod-id = "Orvt0mRa"
# version = "H4bOnadw"
