name: packwiz

on: push

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.info.outputs.name }}
      version: ${{ steps.info.outputs.version }}
      sha: ${{ steps.info.outputs.sha }}
      package: ${{ steps.info.outputs.package }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Prepare environment
        run: GO111MODULE=on go install github.com/freshautomations/stoml@latest
      - name: Get info
        id: info
        run: |
            name=`stoml pack.toml name`
            echo "::set-output name=name::$name"
            version=`stoml pack.toml version`
            echo "::set-output name=version::$version"
            sha=`echo $GITHUB_SHA | cut -c 1-7`
            echo "::set-output name=sha::$sha"
            package=${name}-${version}-rev.${sha}
            echo "::set-output name=package::$package"
  build:
    runs-on: ubuntu-latest
    needs: [info]
    outputs:
      package: ${{ steps.prepare.outputs.package }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Download Packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Prepare environment
        run: |
          touch index.toml
          packwiz refresh

          [ -d .output ] && rm -r .output
          [ -d .temp ] && rm -r .temp
          mkdir -p .output && mkdir -p .temp
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download Packwiz Installer
        run: |
          wget https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar \
           -O .temp/packwiz-installer-bootstrap.jar
      - name: Export Modpack
        run: |
          packwiz curseforge export -o .output/${{ needs.info.outputs.package }}.curseforge.zip
          packwiz modrinth export -o .output/${{ needs.info.outputs.package }}.mrpack


          pack=file://`realpath pack.toml`
          cd .temp && java -jar packwiz-installer-bootstrap.jar -g $pack
          zip -r ../.output/${{ needs.info.outputs.package }}.zip . \
           -x 'packwiz-installer-bootstrap.jar' \
           -x 'packwiz-installer.jar' \
           -x 'packwiz.json'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Modpack
          path: .output/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [info, build]
    steps:
      - name: Download modpack
        uses: actions/download-artifact@v2
        with:
          name: Modpack
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          stripGeneratorNotice: true
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            ${{ needs.info.outputs.package }}.zip
            ${{ needs.info.outputs.package }}.curseforge.zip
            ${{ needs.info.outputs.package }}.mrpack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
