name: pax

on: push

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.info.outputs.name }}
      version: ${{ steps.info.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get info
        id: info
        run: |
            manifestjson=`cat ./modpack/manifest.json`
            name=`echo $(jq -r '.name' <<< "$manifestjson")`
            echo "::set-output name=name::$name"
            version=`echo $(jq -r '.version' <<< "$manifestjson")`
            echo "::set-output name=version::$version"
  build:
    runs-on: ubuntu-latest
    needs: [info]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download PAX
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: froehlichA/pax
          file: "pax"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Export Modpack
        run: |
          sudo chmod +x ./pax
          ./pax export
      - name: Rename Artifact
        run: |
          mv .out/${{ needs.info.outputs.projectname }}.zip .out/${{ needs.info.outputs.projectname }}-${{ needs.info.outputs.version }}-rev.${{  }}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CurseForge
          path: .out/${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.tag }}.zip

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, info]
    steps:
      - name: Download modpack
        uses: actions/download-artifact@v2
        with:
          name: modpack
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          stripGeneratorNotice: true
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: ${{ needs.info.outputs.projectname }}-${{ needs.info.outputs.tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
